version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./web-data/:/app/web-data/
    env_file:
      - docker.env
  nginx:
    image: nginx:1.17.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-data/:/web-data/
      - ./nginx-server.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-data/:/nginx-data/
    env_file:
      - docker.env
    depends_on:
      - web